Improve align frmtcombine docs
GSK-Biostatistics/tfrmt pull request #168
Opened 2022-06-28 18:30 UTC by bzkrouse

resolves #54 
resolves #91

2022-06-28 18:44 UTC, thebioengineer requested changes
Thanks for getting this together. Let me know if my comments don't make sense!

2022-06-28 18:44 UTC, thebioengineer commented on tests/testthat/test-apply_frmt.R
> +  ))
You can assign outputs from expect_warning, so you don't need to rerun the code and suppress warnings.

2022-06-28 18:44 UTC, thebioengineer commented on R/apply_frmt_methods.R
> +  }
Should we add the params as well?

2022-06-29 20:04 UTC, bzkrouse commented on tests/testthat/test-apply_frmt.R
> +  ))
Sure, I added the beginning of the message as I was having issues with the rest. LMK if you think thats sufficient.

2022-06-29 21:11 UTC, thebioengineer approved these changes

2022-06-29 21:11 UTC, thebioengineer commented
Looks great. Thanks!

2022-06-30 07:20 UTC, merged