Create examples
GSK-Biostatistics/tfrmt pull request #207
Opened 2022-07-12 08:39 UTC by shannonhaughton

Adding examples to exported functions

2022-07-14 10:39 UTC, statasaurus approved these changes
🐐 Thank you for adding in all these examples!

2022-07-14 10:42 UTC, statasaurus requested changes
You just need to go through and change the datasets from *_data to data_*

2022-07-14 10:42 UTC, statasaurus commented on R/tfrmt_sigdig.R
> +#'     print_to_gt(labs_data)
I just realized some of these need to be changed to reflect the new data names

2022-07-14 12:55 UTC, shannonhaughton commented
@statasaurus I think there was only one case of this, have done a find in files and cant see any more

2022-07-15 06:58 UTC, statasaurus approved these changes
Amazing 🐄

2022-07-15 07:26 UTC, merged