Col plan advanced
GSK-Biostatistics/tfrmt pull request #270
Opened 2022-08-09 23:50 UTC by thebioengineer

Moving behavior of col_plan and span_structure to:

- col plan acts as a "what you said last is what you expect" situation, but with the order in which things are put changing the column order as we go
- span_structure updated to take multiple columns, the arg name representing the name of the column to apply to. 

**note** documentation has not been updated, as well as many of the tests. Opening this PR for discussion and iteration.

Look at test-col_plan.R for my tests, specifically `Test applying a col_plan - simple`, `Test applying a col_plan - renaming`, and `Test applying a col_plan - ordering on multiple columns` for examples of functioning tests. the `Unorthodox col_plans` has one functioning tests, the second one is failing at the moment but I wanted to chat about them.

2022-08-11 00:14 UTC, thebioengineer commented
col_plan is functioning and tested as we all discussed. I am now working my way through the vignettes and examples across the package.

2022-08-11 12:26 UTC, statasaurus approved these changes
I like how you have broken things apart. I have only done a high level review but I am going to play more in the coming days

2022-08-11 12:45 UTC, statasaurus requested changes
still needs to work through all the bugs includings duplicate naming

2022-08-11 18:35 UTC, thebioengineer commented on R/col_plan.R
> +#'   Defaults to FALSE.
I think based on our discussion that we are okay with it staying the default for now.

2022-08-12 07:23 UTC, statasaurus approved these changes
Looks greeeeaaaat 🐯 (think Tony the tiger)

2022-08-12 07:23 UTC, merged